version: "3.7"

services:
  db:
    image: postgres:16-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
  # pgadmin: // Es un gestro de base de datos
  #   image: dpage/pgadmin4
  #   container_name: pgAdmin
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@nestjs.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_LISTEN_PORT: 80
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - /var/lib/pgadmin
  #   depends_on:
  #     - db